web-ui-file: /var/www/html/pathvector/index.html
origin-communities: ["398057:0:100"]
asn: 398057
irr-server: whois.radb.net
default-route: false

# BGP Communities may be found in `AS398057` aut-num
templates:
  peer:
    local-pref: 250
    filter-irr: true
    filter-as-set: true
    auto-as-set-members: true
    filter-transit-asns: true
    filter-rpki: true
    announce: ["398057:0:100", "398057:0:120"]
    add-on-import: ["398057:0:110"]

  route_server:
    local-pref: 200
    filter-irr: true
    filter-as-set: true
    auto-as-set-members: true
    filter-transit-asns: true
    enforce-peer-nexthop: false
    enforce-first-as: false
    filter-rpki: true
    announce: ["398057:0:100", "398057:0:120"]
    add-on-import: ["398057:0:110", "398057:0:111"]

  downstream:
    local-pref: 260
    filter-irr: true
    filter-as-set: true
    auto-as-set-members: true
    filter-transit-asns: true
    allow-blackhole-community: true
    filter-rpki: true
    announce: ["398057:0:100", "398057:0:120"]
    add-on-import: ["398057:0:120"]

  backbone:
    local-pref: 100
    filter-irr: false
    filter-transit-asns: true
    remove-private-asns: false
    mp-unicast-46: true
    enforce-peer-nexthop: false
    enforce-first-as: false
    prepend-path: [398057]
    announce: ["398057:0:100", "398057:0:110", "398057:0:120"]
    add-on-import: ["398057:0:190"]
